name: PROD Build Workflow

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ASPNETCORE_ENVIRONMENT: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - name: Restore dependencies
        run: npm i

      - run: npm run prepare-release
      - run: npm run lint
